// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIVlRw328JI-NSgjUfHJdXvFT-SDD1AMM',
    appId: '1:356753828943:web:4ca8de45bacc8dbdaf4e3a',
    messagingSenderId: '356753828943',
    projectId: 'foodapp-e9a54',
    authDomain: 'foodapp-e9a54.firebaseapp.com',
    storageBucket: 'foodapp-e9a54.appspot.com',
    measurementId: 'G-87RM9TZCL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYxO3iG5agRbcgWiM8VmTN8z8IDFbkEH8',
    appId: '1:356753828943:android:40809c789cead1a8af4e3a',
    messagingSenderId: '356753828943',
    projectId: 'foodapp-e9a54',
    storageBucket: 'foodapp-e9a54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6C48rI4ttI80yiLanH0PHCRGBx6cB80w',
    appId: '1:356753828943:ios:f9fe50270505f156af4e3a',
    messagingSenderId: '356753828943',
    projectId: 'foodapp-e9a54',
    storageBucket: 'foodapp-e9a54.appspot.com',
    androidClientId: '356753828943-i3hlt85hiossrbcqr7l0o3s8gc57ks39.apps.googleusercontent.com',
    iosClientId: '356753828943-ndopgpcbr6s8i53c6cqgkke54dioeqbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6C48rI4ttI80yiLanH0PHCRGBx6cB80w',
    appId: '1:356753828943:ios:f9fe50270505f156af4e3a',
    messagingSenderId: '356753828943',
    projectId: 'foodapp-e9a54',
    storageBucket: 'foodapp-e9a54.appspot.com',
    androidClientId: '356753828943-i3hlt85hiossrbcqr7l0o3s8gc57ks39.apps.googleusercontent.com',
    iosClientId: '356753828943-ndopgpcbr6s8i53c6cqgkke54dioeqbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikiz',
  );
}
